### ISSUE TITLE
when I run train, some problems came out:

### ISSUE THREAD

**Issue by Sun-Ziyi** [mazzzystar/randomCNN-voice-transfer#3] opened 2019-02-03 08:10 UTC
`C:\Users\Administrator\AppData\Local\Programs\Python\Python35\python.exe E:/PyCharmProject/randomCNN-voice-transfer-master3/train.py
Traceback (most recent call last):
  File "E:/PyCharmProject/randomCNN-voice-transfer-master3/train.py", line 4, in <module>
    from torch.autograd import Variable
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\__init__.py", line 84, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的程序。

Process finished with exit code 1`

**Comment by Sun-Ziyi** [comment] 2019-02-03 10:43
after solving the problem above, I run train:
`C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe E:/PyCharmProject/randomCNN-voice-transfer-master3/train.py
Traceback (most recent call last):
  File "E:/PyCharmProject/randomCNN-voice-transfer-master3/train.py", line 5, in <module>
    from utils import *
  File "E:\PyCharmProject\randomCNN-voice-transfer-master3\utils.py", line 1, in <module>
    import librosa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\__init__.py", line 14, in <module>
    from . import decompose
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\decompose.py", line 19, in <module>
    import sklearn.decomposition
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\decomposition\__init__.py", line 10, in <module>
    from .kernel_pca import KernelPCA
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\decomposition\kernel_pca.py", line 14, in <module>
    from ..preprocessing import KernelCenterer
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\preprocessing\__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\preprocessing\_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\utils\testing.py", line 21, in <module>
    import scipy.io
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\matlab\__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\matlab\mio.py", line 12, in <module>
    from .mio5 import MatFile5Reader, MatFile5Writer
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

Process finished with exit code 1`

**Comment by mazzzystar** [comment] 2019-02-03 12:07
@Sun-Ziyi 
I don't think this error is caused by this project, maybe you should reinstall `librosa`.

**Comment by Sun-Ziyi** [comment] 2019-02-03 16:26
@mazzzystar , thank u to your reply
but, some problem came out again:
`C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe "E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py"
355
257
torch.Size([1, 1, 257, 355])
torch.Size([1, 1, 257, 355])
Traceback (most recent call last):
  File "E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py", line 58, in <module>
    a_G_var = Variable(torch.randn(a_content_torch.shape).cuda() * 1e-3, requires_grad=True)
RuntimeError: torch.cuda.FloatTensor is not enabled.
`
looking forward to your reply

**Comment by mazzzystar** [comment] 2019-02-03 16:44
@Sun-Ziyi 
This is because you tried to run it on `non-GPU` machine.
Actually running on `CPU` is almost `10x` slower than on `GPU`, if you still have to run it on `CPU`, try to change all `var.cuda` to `var`, like line 58:
```python
a_G_var = Variable(torch.randn(a_content_torch.shape).cuda() * 1e-3, requires_grad=True)
--->
a_G_var = Variable(torch.randn(a_content_torch.shape) * 1e-3, requires_grad=True)
```

**Comment by Sun-Ziyi** [comment] 2019-02-03 17:01
@mazzzystar. thank you very much. It seems to be too slow indeed:
![image](https://user-images.githubusercontent.com/47275308/52179662-fddd2c00-2817-11e9-8a10-3d8c11c2ddcb.png)

Additionally, I have some ideas on the topic of voice transfer, but I dont know whether it will work.
So, can I send my document to your qq email and hope your suggestion?

**Comment by mazzzystar** [comment] 2019-02-04 01:44
@Sun-Ziyi 
可以～ 虽然我也研究得也很有限: )

**Comment by Sun-Ziyi** [comment] 2019-02-04 03:17
@mazzzystar 
1. thank you, 我已经发送pdf到你的qq邮箱，希望您能查看
2. besides, 运行又遇到问题了，似乎卡在这里了：
`C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe "E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py"
355
257
torch.Size([1, 1, 257, 355])
torch.Size([1, 1, 257, 355])
E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py:99: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
1000 5.0% 243m 12s content_loss:4.241981 style_loss:121.804543 total_loss:126.046524
  content_loss.data[0],
E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py:100: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  style_loss.data[0], loss.data[0]))
E:/PyCharmProject/3 randomCNN-voice-transfer-master/train.py:101: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  current_loss += loss.data[0]
2000 10.0% 441m 42s content_loss:4.173096 style_loss:19.166868 total_loss:23.339964`
3. 怎样做才可以使得代码运行在CPU上呢？

**Comment by mazzzystar** [comment] 2019-02-04 10:29
1. 这几天在过年，可能等春节过后才能看看～
2.这个`UserWarning`不需要在乎，它是说`PyTorch 0.4`支持使用`data.item()`来获取数据。
3.把所有`XXX.cuda()`修改为`XXX`

**Comment by mazzzystar** [comment] 2019-02-13 06:56
Close the issue because of in-activate, feel free to reopen.

**Closed as completed by mazzzystar** 2019-02-13 06:56 UTC
